#!/bin/bash

source /etc/profile
source /root/.bashrc

for redis_port in $(cat redis-server.config |grep -v -E "^#" |awk '{print $2}');do
  redis_pass="$(cat redis-server.config |grep -v -E "^#" |grep $redis_port |awk '{print $3}')"
  redis_host="$(cat redis-server.config |grep -v -E "^#" |grep $redis_port |awk '{print $1}')"
  tpstest="$(/usr/local/bin/redis-cli -h $redis_host -p $redis_port -a $redis_pass info all |grep "instantaneous_ops_per_sec" |awk -F ":" '{print $2}')"
  /usr/local/bin/redis-cli -h $redis_host -p $redis_port -a $redis_pass info all |grep cmdstat > ./cmdstat.log
  calls_max=$(cat cmdstat.log |awk -F "," '{print $1}' |awk -F "=" '{print $2}' |sort -n -r |head -1)
  calls_name=$(cat cmdstat.log |grep $calls_max |awk -F ":" '{print $1}')
  usec_per_call=$(cat cmdstat.log |grep $calls_max |awk -F "," '{print $3}' |awk -F "=" '{print $2}')
  #echo "`date +%Y-%m-%d-%H:%M:%S` tps:$tpstest\ calls_name:$calls_name usec_per_call:$usec_per_call" >> ./redis_status.log
  echo "`date +%Y-%m-%d-%H:%M:%S` calls_name:$calls_name usec_per_call:$usec_per_call" >> /var/log/redis-$redis_port-status.log
  echo "                    tps:$tpstest" >> /var/log/redis-$redis_port-status.log
  rm ./cmdstat.log
done
